🔧 Improve testing script

diff --git a/script/http/perf_test b/script/http/perf_test
--- a/script/http/perf_test
+++ b/script/http/perf_test
@@ -18,10 +18,8 @@ clear
 
 echo "Building..."
 
-if "$BUILD_SCRIPT_PATH"; then
-    echo "Build success ✔️"
-else
-    echo "Build failed ❌"
+if ! "$BUILD_SCRIPT_PATH"; then
+    echo "Building failed ❌"
 
     exit 1
 fi
diff --git a/script/http/test b/script/http/test
--- a/script/http/test
+++ b/script/http/test
@@ -15,7 +15,7 @@ if [ $# -gt 2 ]; then
 fi
 
 number_of_seconds_to_test=${1:-2} # test for 2 seconds each time by default
-repeat_times=${2:-5}              # repeat for 5 times total by default
+repeat_times=${2:-1}              # repeat once by default
 
 if ! [[ "$number_of_seconds_to_test" =~ ^-?[0-9]+$ ]] || ! [[ "$repeat_times" =~ ^-?[0-9]+$ ]]; then
     echo "Usage: $0 <seconds> <repeat>"
@@ -29,10 +29,8 @@ echo "WebBench test time (seconds): $number_of_seconds_to_test"
 
 echo "Building..."
 
-if "$BUILD_SCRIPT_PATH"; then
-    echo "Build success ✔️"
-else
-    echo "Build failed ❌"
+if ! "$BUILD_SCRIPT_PATH"; then
+    echo "Building failed ❌"
 
     exit 1
 fi
